config/routes.rb
Rails.application.routes.draw do
  resources :reflections

  get 'sessions/new'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'
  
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reflection.rb
class Reflection < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/reflections_controller.rb
class ReflectionsController < ApplicationController
  before_action :set_reflection, only: %i[ show edit update destroy ]

  # GET /reflections or /reflections.json
  def index
    @reflections = Reflection.all
  end

  # GET /reflections/1 or /reflections/1.json
  def show
  end

  # GET /reflections/new
  def new
    @reflection = Reflection.new
  end

  # GET /reflections/1/edit
  def edit
  end

  # POST /reflections or /reflections.json
  def create
    @reflection = Reflection.new(reflection_params)

    respond_to do |format|
      if @reflection.save
        format.html { redirect_to @reflection, notice: "Reflection was successfully created." }
        format.json { render :show, status: :created, location: @reflection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reflection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reflections/1 or /reflections/1.json
  def update
    respond_to do |format|
      if @reflection.update(reflection_params)
        format.html { redirect_to @reflection, notice: "Reflection was successfully updated." }
        format.json { render :show, status: :ok, location: @reflection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reflection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reflections/1 or /reflections/1.json
  def destroy
    @reflection.destroy
    respond_to do |format|
      format.html { redirect_to reflections_url, notice: "Reflection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reflection
      @reflection = Reflection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reflection_params
      params.require(:reflection).permit(:student_name, :block, :teacher_name, :project_name, :project_type, :conduct, :leadership, :work, :creativity, :collaboration, :thinking, :communication, :comments, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create  
        @user = User.find_by(username: params[:user][:username])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to root_path, flash:{notice: "You are now signed in."}
        else
            redirect_to signin_path, flash:{notice: "Invalid credentials. Please try again"}
        end
    end

    def destroy
        session.clear
        redirect_to signin_path, flash:{notice: "You are now signed out."}
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reflections_helper.rb
module ReflectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="col-md-8 offset-md-2 info">
    <h1 class="text-center">ReflectionTime</h1>
    <p class="text-center">A place for you to reflect on your school projects.</p>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Reflection Time</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to 'Reflection Time', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"><i class="fas fa-bars" style="color:#fff; font-size:28px;"></i></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>
        
        
          <li class="nav-item">
            <%= link_to "All Reflections", reflections_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Your Reflections", users_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Reflection", new_reflection_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", signout_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", users_edit_path, class:"nav-link" %>
          </li>

          
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", 'sessions/new', class:"nav-link" %>
          </li>
        
      </ul>
    </div>
  </div>
</nav>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reflections/_form.html.erb
<%= form_with(model: reflection) do |form| %>
  <% if reflection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reflection.errors.count, "error") %> prohibited this reflection from being saved:</h2>

      <ul>
        <% reflection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_name %>
    <%= form.text_field :student_name %>
  </div>

  <div class="field">
    <%= form.label :block %>
    <%= form.text_field :block %>
  </div>

  <div class="field">
    <%= form.label :teacher_name %>
    <%= form.text_field :teacher_name %>
  </div>

  <div class="field">
    <%= form.label :project_name %>
    <%= form.text_field :project_name %>
  </div>

  <div class="field">
    <%= form.label :project_type %>
    <%= form.text_field :project_type %>
  </div>

  <div class="field">
    <%= form.label :conduct %>
    <%= form.text_field :conduct %>
  </div>

  <div class="field">
    <%= form.label :leadership %>
    <%= form.text_field :leadership %>
  </div>

  <div class="field">
    <%= form.label :work %>
    <%= form.text_field :work %>
  </div>

  <div class="field">
    <%= form.label :creativity %>
    <%= form.text_field :creativity %>
  </div>

  <div class="field">
    <%= form.label :collaboration %>
    <%= form.text_field :collaboration %>
  </div>

  <div class="field">
    <%= form.label :thinking %>
    <%= form.text_field :thinking %>
  </div>

  <div class="field">
    <%= form.label :communication %>
    <%= form.text_field :communication %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reflections/edit.html.erb
<h1>Editing Reflection</h1>

<%= render 'form', reflection: @reflection %>

<%= link_to 'Show', @reflection %> |
<%= link_to 'Back', reflections_path %>

app/views/reflections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reflections</h1>

<table>
  <thead>
    <tr>
      <th>Student name</th>
      <th>Block</th>
      <th>Teacher name</th>
      <th>Project name</th>
      <th>Project type</th>
      <th>Conduct</th>
      <th>Leadership</th>
      <th>Work</th>
      <th>Creativity</th>
      <th>Collaboration</th>
      <th>Thinking</th>
      <th>Communication</th>
      <th>Comments</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reflections.each do |reflection| %>
      <tr>
        <td><%= reflection.student_name %></td>
        <td><%= reflection.block %></td>
        <td><%= reflection.teacher_name %></td>
        <td><%= reflection.project_name %></td>
        <td><%= reflection.project_type %></td>
        <td><%= reflection.conduct %></td>
        <td><%= reflection.leadership %></td>
        <td><%= reflection.work %></td>
        <td><%= reflection.creativity %></td>
        <td><%= reflection.collaboration %></td>
        <td><%= reflection.thinking %></td>
        <td><%= reflection.communication %></td>
        <td><%= reflection.comments %></td>
        <td><%= reflection.user_id %></td>
        <td><%= link_to 'Show', reflection %></td>
        <td><%= link_to 'Edit', edit_reflection_path(reflection) %></td>
        <td><%= link_to 'Destroy', reflection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reflection', new_reflection_path %>

app/views/reflections/new.html.erb
<h1>New Reflection</h1>

<%= render 'form', reflection: @reflection %>

<%= link_to 'Back', reflections_path %>

app/views/reflections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student name:</strong>
  <%= @reflection.student_name %>
</p>

<p>
  <strong>Block:</strong>
  <%= @reflection.block %>
</p>

<p>
  <strong>Teacher name:</strong>
  <%= @reflection.teacher_name %>
</p>

<p>
  <strong>Project name:</strong>
  <%= @reflection.project_name %>
</p>

<p>
  <strong>Project type:</strong>
  <%= @reflection.project_type %>
</p>

<p>
  <strong>Conduct:</strong>
  <%= @reflection.conduct %>
</p>

<p>
  <strong>Leadership:</strong>
  <%= @reflection.leadership %>
</p>

<p>
  <strong>Work:</strong>
  <%= @reflection.work %>
</p>

<p>
  <strong>Creativity:</strong>
  <%= @reflection.creativity %>
</p>

<p>
  <strong>Collaboration:</strong>
  <%= @reflection.collaboration %>
</p>

<p>
  <strong>Thinking:</strong>
  <%= @reflection.thinking %>
</p>

<p>
  <strong>Communication:</strong>
  <%= @reflection.communication %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @reflection.comments %>
</p>

<p>
  <strong>User:</strong>
  <%= @reflection.user_id %>
</p>

<%= link_to 'Edit', edit_reflection_path(@reflection) %> |
<%= link_to 'Back', reflections_path %>